services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: videobites-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - DOWNLOAD_DIR=/app/data

volumes:
  data:
    driver: local
