services:
  videobites:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: videobites
    restart: unless-stopped
    ports:
      - "80:3000"
    volumes:
      - ./data:/app/data
    environment:
      - DOWNLOAD_DIR=/app/data

volumes:
  data:
    driver: local