services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: videobites-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - DOWNLOAD_DIR=/app/data

  frontend:
    image: nginx:alpine
    container_name: videobites-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./data:/usr/share/nginx/html/data:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  data:
    driver: local